export const state = {
  // projects: [
  //     {
  //       scope: 0,
  //       name: 'Blackjack',
  //       group: 'game',
  //       img: '/masonry/games/blackjack/001.png',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Phoneography',
  //       group: 'phoneography',
  //       img: '/masonry/phoneography/001.jpg',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Monopoly',
  //       group: 'game',
  //       img: '/masonry/games/monopoly/001.png',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Phoneography',
  //       group: 'phoneography',
  //       img: '/masonry/phoneography/002.jpg',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Music with Celine',
  //       group: 'music',
  //       img: '/masonry/music/celine/003.jpg',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Phoneography',
  //       group: 'phoneography',
  //       img: '/masonry/phoneography/003.jpg',
  //       video: null,
  //     },
  //     {
  //       scope: 0,
  //       name: 'Photography',
  //       group: 'photography',
  //       img: '/masonry/photography/001.jpg',
  //       video: null,
  //     },
  //   ],
  projects: [
    // Acoustic Concert
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/001.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/002.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/003.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/004.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/005.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/006.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/007.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/008.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/009.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/010.jpg',
      video: null,
    },
    {
      order: 0,
      link: 'concert',
      name: 'Acoustic Concert',
      group: 'acoustic-concert',
      category: 'acoustic-concert',
      img: '/masonry/concert/011.jpg',
      video: null,
    },
    // Design Illustration | Cartoon
    {
      order: 0,
      link: 'illustration',
      name: 'Cartoon Illustration',
      group: 'cartoon-illustration',
      category: 'illustration',
      img: '/masonry/design-illustrations/cartoon-illustration/001.jpg',
      video: null,
    },
    // Design Illustration | Cyclo
    {
      order: 0,
      link: 'illustration',
      name: 'Cyclo',
      group: 'cyclo',
      category: 'illustration',
      img: '/masonry/design-illustrations/cyclo/cyclo.gif',
      video: null,
    },
    // Design Illustration | Decibels
    {
      order: 0,
      link: 'illustration',
      name: 'Decibels',
      group: 'decibels',
      category: 'illustration',
      img: '/masonry/design-illustrations/decibels/001.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Decibels',
      group: 'decibels',
      category: 'illustration',
      img: '/masonry/design-illustrations/decibels/002.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Decibels',
      group: 'decibels',
      category: 'illustration',
      img: '/masonry/design-illustrations/decibels/003.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Decibels',
      group: 'decibels',
      category: 'illustration',
      img: '/masonry/design-illustrations/decibels/004.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Decibels',
      group: 'decibels',
      category: 'illustration',
      img: '/masonry/design-illustrations/decibels/005.png',
      video: null,
    },
    // Design Illustration | Mature Minds
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/001.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/002.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/003.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/004.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/005.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/006.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Mature Minds',
      group: 'mature-minds',
      category: 'illustration',
      img: '/masonry/design-illustrations/mature-minds/006.png',
      video: null,
    },
    // Design Illustration | Cartoon
    {
      order: 0,
      link: 'illustration',
      name: 'Nush',
      group: 'nush',
      category: 'illustration',
      img: '/masonry/design-illustrations/nush/001.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Nush',
      group: 'nush',
      category: 'illustration',
      img: '/masonry/design-illustrations/nush/001.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Nush',
      group: 'nush',
      category: 'illustration',
      img: '/masonry/design-illustrations/nush/002.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Nush',
      group: 'nush',
      category: 'illustration',
      img: '/masonry/design-illustrations/nush/003.png',
      video: null,
    },
    {
      order: 0,
      link: 'illustration',
      name: 'Nush',
      group: 'nush',
      category: 'illustration',
      img: '/masonry/design-illustrations/nush/004.png',
      video: null,
    },
  ],
}
